#!/usr/bin/env bash

PREV_TOTAL=0
PREV_IDLE=0

while true; do
  # Gather all CPU stats
  CPU=(`sed -n 's/^cpu\s//p' /proc/stat`)
  IDLE=${CPU[3]}

  # Determine total CPU time
  TOTAL=0
  for VALUE in "${CPU[@]}"; do
    let "TOTAL=$TOTAL+$VALUE"
  done

  # Calculate the ammount of CPU load since the last check
  let "DIFF_IDLE=$IDLE-$PREV_IDLE"
  let "DIFF_TOTAL=$TOTAL-$PREV_TOTAL"
  let "DIFF_USAGE=(1000*($DIFF_TOTAL-$DIFF_IDLE)/$DIFF_TOTAL+5)/10"
  echo -en "\rCPU: $DIFF_USAGE%  \b\b"

  # Save these values for the next check
  PREV_TOTAL="$TOTAL"
  PREV_IDLE="$IDLE"
  
  sleep 1
done