# Generated by Django 2.1.5 on 2019-02-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=20)),
                ('added_date', models.DateTimeField(verbose_name='Date Added')),
                ('creator', models.CharField(max_length=20)),
            ],
        ),
    ]
