# Generated by Django 2.1.5 on 2019-02-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('added_date', models.DateTimeField(verbose_name='Date Added')),
                ('apps', models.CharField(choices=[('Stock.a', 'Stock.app\n')], max_length=20)),
            ],
        ),
    ]
