# Generated by Django 2.1.5 on 2019-03-21 16:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_user_apps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ticker', models.CharField(choices=[('0', 'AAPL'), ('1', 'MSFT'), ('2', 'FB'), ('3', 'SPY'), ('4', 'TVIX')], max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='creator',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Users.User'),
        ),
    ]
