# Generated by Django 2.1.5 on 2019-03-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20190321_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='Ticker',
            field=models.CharField(choices=[('AAPL', '0'), ('MSFT', '1'), ('FB', '2'), ('SPY', '3'), ('TVIX', '4')], max_length=5),
        ),
    ]
